export enum Category {
    NONE = '',
    ALL = "Todas",
    AIRE_ACONDICIONADO = 'Aire Acondicionado',
    VENTILADOR = 'Ventiladores', 
    TELEVISORES = 'Televisores', 
    AURICULARES = 'Auriculares', 
    PARLANTES = 'Parlantes', 
    HELADERAS = 'Heladeras', 
    LAVARROPAS = 'Lavarropas',
    ASPIRADORAS = 'Aspiradoras',
    MICROONDAS = 'Microondas', 
    CELULARES = 'Celulares',
    NOTEBOOKS = 'Notebooks',
    TABLETS = 'Tablets', 
    IMPRESORAS = 'Impresoras', 
    COMPUTADORAS_ESCRITORIO = 'Computadoras de Escritorio',
    TECLADOS = 'Teclados',
    MOUSES = 'Mouses'
}
